# Generated by Django 3.2.5 on 2021-10-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211025_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='common_status',
            field=models.CharField(default='UNDEFINED', max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
