# Generated by Django 3.2.5 on 2021-10-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211025_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='tds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
